drop table if exists board CASCADE;
create table board
(
 id bigint generated by default as identity,
 title varchar(255),
 content varchar(255),
 writer varchar(255),
 delete_yn char,
 hits number(5),
 create_date datetime,

primary key (id)
);